name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: "-Xmx6G -XX:+UseG1GC"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Test
        run: sbt testKit/test

  format:
    runs-on: ubuntu-latest
    env:
      SBT_OPTS: "-Dsbt.ci=true"
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Check Formatting
        run: sbt check
